<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>spring-boot-starter-parent</artifactId>
        <groupId>org.springframework.boot</groupId>
        <version>3.2.7</version>
    </parent>
    <groupId>com.luyu</groupId>
    <artifactId>medicine_inventory_system</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>common</module>
        <module>entity</module>
        <module>repository</module>
        <module>service</module>
        <module>web</module>
        <module>security</module>
        <module>notice</module>
    </modules>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <common>1.0-SNAPSHOT</common>
        <security>1.0-SNAPSHOT</security>
        <entity>1.0-SNAPSHOT</entity>
        <repository>1.0-SNAPSHOT</repository>
        <service>1.0-SNAPSHOT</service>
        <web>1.0-SNAPSHOT</web>
        <notice>1.0-SNAPSHOT</notice>

        <mybatis-plus>3.5.5</mybatis-plus>
        <lombok.version>1.18.32</lombok.version>
        <jjwt>0.9.1</jjwt>
        <jaxb-api>2.3.1</jaxb-api>
        <mysql.version>8.3.0</mysql.version>
        <mybatis.version>3.0.3</mybatis.version>
        <jackson.version>2.15.4</jackson.version>
        <common-lang3>3.12.0</common-lang3>
        <poi.ooxml>5.2.3</poi.ooxml>
        <poi>5.2.3</poi>
    </properties>
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>common</artifactId>
            <version>${common}</version>
        </dependency>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>security</artifactId>
            <version>${security}</version>
        </dependency>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>entity</artifactId>
            <version>${entity}</version>
        </dependency>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>repository</artifactId>
            <version>${repository}</version>
        </dependency>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>service</artifactId>
            <version>${service}</version>
        </dependency>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>web</artifactId>
            <version>${web}</version>
        </dependency>
        <dependency>
            <groupId>com.luyu</groupId>
            <artifactId>notice</artifactId>
            <version>${notice}</version>
        </dependency>


        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis-plus}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.mybatis</groupId>
                    <artifactId>mybatis-spring</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.ooxml}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${poi}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${common-lang3}</version>
        </dependency>
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-spring</artifactId>
            <version>${mybatis.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>io.jsonwebtoken</groupId>
            <artifactId>jjwt</artifactId>
            <version>${jjwt}</version>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>${jaxb-api}</version>
        </dependency>
        <dependency>
            <groupId>com.github.wechatpay-apiv3</groupId>
            <artifactId>wechatpay-apache-httpclient</artifactId>
            <version>0.4.8</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.version}</version>
        </dependency>
    </dependencies>
</dependencyManagement>
</project>